#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arjasb_mobile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="arjasb-mobile-DB")]
	public partial class linqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertauthenticatetbl(authenticatetbl instance);
    partial void Updateauthenticatetbl(authenticatetbl instance);
    partial void Deleteauthenticatetbl(authenticatetbl instance);
    partial void InsertDefecttbl(Defecttbl instance);
    partial void UpdateDefecttbl(Defecttbl instance);
    partial void DeleteDefecttbl(Defecttbl instance);
    partial void InsertDeviceJoncDefecttbl(DeviceJoncDefecttbl instance);
    partial void UpdateDeviceJoncDefecttbl(DeviceJoncDefecttbl instance);
    partial void DeleteDeviceJoncDefecttbl(DeviceJoncDefecttbl instance);
    partial void InsertDevicetbl(Devicetbl instance);
    partial void UpdateDevicetbl(Devicetbl instance);
    partial void DeleteDevicetbl(Devicetbl instance);
    partial void Insertordertbl(ordertbl instance);
    partial void Updateordertbl(ordertbl instance);
    partial void Deleteordertbl(ordertbl instance);
    partial void Insertownertbl(ownertbl instance);
    partial void Updateownertbl(ownertbl instance);
    partial void Deleteownertbl(ownertbl instance);
    partial void InsertPart(Part instance);
    partial void UpdatePart(Part instance);
    partial void DeletePart(Part instance);
    partial void Insertserviceman(serviceman instance);
    partial void Updateserviceman(serviceman instance);
    partial void Deleteserviceman(serviceman instance);
    #endregion
		
		public linqDataContext() : 
				base(global::arjasb_mobile.Properties.Settings.Default.arjasb_mobile_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<authenticatetbl> authenticatetbls
		{
			get
			{
				return this.GetTable<authenticatetbl>();
			}
		}
		
		public System.Data.Linq.Table<Defecttbl> Defecttbls
		{
			get
			{
				return this.GetTable<Defecttbl>();
			}
		}
		
		public System.Data.Linq.Table<DeviceJoncDefecttbl> DeviceJoncDefecttbls
		{
			get
			{
				return this.GetTable<DeviceJoncDefecttbl>();
			}
		}
		
		public System.Data.Linq.Table<Devicetbl> Devicetbls
		{
			get
			{
				return this.GetTable<Devicetbl>();
			}
		}
		
		public System.Data.Linq.Table<ordertbl> ordertbls
		{
			get
			{
				return this.GetTable<ordertbl>();
			}
		}
		
		public System.Data.Linq.Table<ownertbl> ownertbls
		{
			get
			{
				return this.GetTable<ownertbl>();
			}
		}
		
		public System.Data.Linq.Table<Part> Parts
		{
			get
			{
				return this.GetTable<Part>();
			}
		}
		
		public System.Data.Linq.Table<serviceman> servicemans
		{
			get
			{
				return this.GetTable<serviceman>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ApplyDefect")]
		public int ApplyDefect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DefectType", DbType="NVarChar(50)")] string defectType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Defect", DbType="NVarChar(100)")] string defect, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Solution", DbType="NVarChar(500)")] string solution, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsefullFileAdr", DbType="NVarChar(100)")] string usefullFileAdr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsefullUrls", DbType="NVarChar(100)")] string usefullUrls)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), defectType, defect, solution, usefullFileAdr, usefullUrls);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ApplyOrderOwnerDeviceTBL")]
		public int ApplyOrderOwnerDeviceTBL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RAM", DbType="Bit")] System.Nullable<bool> rAM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Battery", DbType="Bit")] System.Nullable<bool> battery, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Charger", DbType="Bit")] System.Nullable<bool> charger, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrentStatus", DbType="Bit")] System.Nullable<bool> currentStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TakeDate", DbType="NVarChar(15)")] string takeDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> payment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(70)")] string expretion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string owner, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(50)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceManufacturer", DbType="NVarChar(50)")] string deviceManufacturer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceName", DbType="NVarChar(50)")] string deviceName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), srvId, rAM, battery, charger, currentStatus, takeDate, payment, expretion, owner, phoneNumber, deviceManufacturer, deviceName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ApplyPart")]
		public int ApplyPart([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartName", DbType="NVarChar(30)")] string partName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> alarm)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partName, price, alarm);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ApplySrvman")]
		public int ApplySrvman([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(30)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string expert)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, lastName, expert);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChangeDeviceSrvMan")]
		public int ChangeDeviceSrvMan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId, srvId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChangeDeviceState")]
		public int ChangeDeviceState([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> b, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepairedDate", DbType="NVarChar(15)")] string repairedDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId, b, repairedDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChechOrderId")]
		public ISingleResult<ChechOrderIdResult> ChechOrderId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId);
			return ((ISingleResult<ChechOrderIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteOrder")]
		public int DeleteOrder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeletePart")]
		public int DeletePart([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartId", DbType="Int")] System.Nullable<int> partId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DelSrvman")]
		public int DelSrvman([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), srvId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditOrder")]
		public int EditOrder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RAM", DbType="Bit")] System.Nullable<bool> rAM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Battery", DbType="Bit")] System.Nullable<bool> battery, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Charger", DbType="Bit")] System.Nullable<bool> charger, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TakeDate", DbType="NVarChar(15)")] string takeDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> payment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(70)")] string expretion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string owner, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(50)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceManufacturer", DbType="NVarChar(50)")] string deviceManufacturer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceName", DbType="NVarChar(50)")] string deviceName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId, srvId, rAM, battery, charger, takeDate, payment, expretion, owner, phoneNumber, deviceManufacturer, deviceName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditPart")]
		public int EditPart([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartId", DbType="Int")] System.Nullable<int> partId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartName", DbType="NVarChar(30)")] string partName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> alarm)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partId, partName, price, alarm);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FreeDeviceSrvMan")]
		public int FreeDeviceSrvMan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId, srvId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectPartsforDevice")]
		public int SelectPartsforDevice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartId", DbType="Int")] System.Nullable<int> partId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AssembleDate", DbType="NVarChar(15)")] string assembleDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partId, orderId, assembleDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShearchPart")]
		public ISingleResult<ShearchPartResult> ShearchPart([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartName", DbType="NVarChar(30)")] string partName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partName);
			return ((ISingleResult<ShearchPartResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDefectSolution")]
		public ISingleResult<ShowDefectSolutionResult> ShowDefectSolution([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceName", DbType="NVarChar(50)")] string deviceName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DefectType", DbType="NVarChar(50)")] string defectType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Defect", DbType="NVarChar(100)")] string defect)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceName, defectType, defect);
			return ((ISingleResult<ShowDefectSolutionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceDefect")]
		public ISingleResult<ShowDeviceDefectResult> ShowDeviceDefect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DefectType", DbType="NVarChar(50)")] string defectType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceName", DbType="NVarChar(50)")] string deviceName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), defectType, deviceName);
			return ((ISingleResult<ShowDeviceDefectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceManufacturer")]
		public ISingleResult<ShowDeviceManufacturerResult> ShowDeviceManufacturer()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowDeviceManufacturerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceNames")]
		public ISingleResult<ShowDeviceNamesResult> ShowDeviceNames()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowDeviceNamesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceNamesbyCategorizing")]
		public ISingleResult<ShowDeviceNamesbyCategorizingResult> ShowDeviceNamesbyCategorizing([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceManufacturer", DbType="NVarChar(50)")] string deviceManufacturer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceManufacturer);
			return ((ISingleResult<ShowDeviceNamesbyCategorizingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceNSofSrvman")]
		public ISingleResult<ShowDeviceNSofSrvmanResult> ShowDeviceNSofSrvman()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowDeviceNSofSrvmanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceReapairing")]
		public ISingleResult<ShowDeviceReapairingResult> ShowDeviceReapairing([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), srvId);
			return ((ISingleResult<ShowDeviceReapairingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceRepaired")]
		public ISingleResult<ShowDeviceRepairedResult> ShowDeviceRepaired([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), srvId);
			return ((ISingleResult<ShowDeviceRepairedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDeviceSofSrvman")]
		public ISingleResult<ShowDeviceSofSrvmanResult> ShowDeviceSofSrvman([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrvId", DbType="Int")] System.Nullable<int> srvId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), srvId);
			return ((ISingleResult<ShowDeviceSofSrvmanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowOrderMenu")]
		public ISingleResult<ShowOrderMenuResult> ShowOrderMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="NVarChar(30)")] string orderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceName", DbType="NVarChar(30)")] string deviceName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string owner)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId, deviceName, owner);
			return ((ISingleResult<ShowOrderMenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowParts")]
		public ISingleResult<ShowPartsResult> ShowParts()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowPartsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowPartsforDevice")]
		public ISingleResult<ShowPartsforDeviceResult> ShowPartsforDevice()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowPartsforDeviceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowSrvman")]
		public ISingleResult<ShowSrvmanResult> ShowSrvman()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowSrvmanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowSrvmanExpert")]
		public ISingleResult<ShowSrvmanExpertResult> ShowSrvmanExpert()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowSrvmanExpertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateExpr")]
		public int UpdateExpr([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderId", DbType="Int")] System.Nullable<int> orderId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(70)")] string expretion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderId, expretion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GivePartIdTakePartName", IsComposable=true)]
		public System.Nullable<int> GivePartIdTakePartName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PartName", DbType="NVarChar(30)")] string partName)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partName).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MaxOrderId", IsComposable=true)]
		public System.Nullable<int> MaxOrderId()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MaxPartId", IsComposable=true)]
		public System.Nullable<int> MaxPartId()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MaxSrvId", IsComposable=true)]
		public System.Nullable<int> MaxSrvId()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDefectTypebyCategorizing")]
		public ISingleResult<ShowDefectTypebyCategorizingResult> ShowDefectTypebyCategorizing([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceName", DbType="NVarChar(50)")] string deviceName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceName);
			return ((ISingleResult<ShowDefectTypebyCategorizingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowDefectType")]
		public ISingleResult<ShowDefectTypeResult> ShowDefectType()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowDefectTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ApplyDevice")]
		public int ApplyDevice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceManufacturer", DbType="NVarChar(50)")] string deviceManufacturer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceName", DbType="NVarChar(50)")] string deviceName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceManufacturer, deviceName);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.authenticatetbl")]
	public partial class authenticatetbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AuthenticateId;
		
		private string _users;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthenticateIdChanging(int value);
    partial void OnAuthenticateIdChanged();
    partial void OnusersChanging(string value);
    partial void OnusersChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public authenticatetbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthenticateId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AuthenticateId
		{
			get
			{
				return this._AuthenticateId;
			}
			set
			{
				if ((this._AuthenticateId != value))
				{
					this.OnAuthenticateIdChanging(value);
					this.SendPropertyChanging();
					this._AuthenticateId = value;
					this.SendPropertyChanged("AuthenticateId");
					this.OnAuthenticateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users", DbType="NVarChar(50)")]
		public string users
		{
			get
			{
				return this._users;
			}
			set
			{
				if ((this._users != value))
				{
					this.OnusersChanging(value);
					this.SendPropertyChanging();
					this._users = value;
					this.SendPropertyChanged("users");
					this.OnusersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Defecttbl")]
	public partial class Defecttbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DefectId;
		
		private string _DefectType;
		
		private string _Defect;
		
		private string _Solution;
		
		private string _UsefullFileAdr;
		
		private string _UsefullUrls;
		
		private System.Nullable<int> _MounthPeak;
		
		private EntitySet<DeviceJoncDefecttbl> _DeviceJoncDefecttbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDefectIdChanging(int value);
    partial void OnDefectIdChanged();
    partial void OnDefectTypeChanging(string value);
    partial void OnDefectTypeChanged();
    partial void OnDefectChanging(string value);
    partial void OnDefectChanged();
    partial void OnSolutionChanging(string value);
    partial void OnSolutionChanged();
    partial void OnUsefullFileAdrChanging(string value);
    partial void OnUsefullFileAdrChanged();
    partial void OnUsefullUrlsChanging(string value);
    partial void OnUsefullUrlsChanged();
    partial void OnMounthPeakChanging(System.Nullable<int> value);
    partial void OnMounthPeakChanged();
    #endregion
		
		public Defecttbl()
		{
			this._DeviceJoncDefecttbls = new EntitySet<DeviceJoncDefecttbl>(new Action<DeviceJoncDefecttbl>(this.attach_DeviceJoncDefecttbls), new Action<DeviceJoncDefecttbl>(this.detach_DeviceJoncDefecttbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefectId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DefectId
		{
			get
			{
				return this._DefectId;
			}
			set
			{
				if ((this._DefectId != value))
				{
					this.OnDefectIdChanging(value);
					this.SendPropertyChanging();
					this._DefectId = value;
					this.SendPropertyChanged("DefectId");
					this.OnDefectIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefectType", DbType="NVarChar(50)")]
		public string DefectType
		{
			get
			{
				return this._DefectType;
			}
			set
			{
				if ((this._DefectType != value))
				{
					this.OnDefectTypeChanging(value);
					this.SendPropertyChanging();
					this._DefectType = value;
					this.SendPropertyChanged("DefectType");
					this.OnDefectTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Defect", DbType="NVarChar(100)")]
		public string Defect
		{
			get
			{
				return this._Defect;
			}
			set
			{
				if ((this._Defect != value))
				{
					this.OnDefectChanging(value);
					this.SendPropertyChanging();
					this._Defect = value;
					this.SendPropertyChanged("Defect");
					this.OnDefectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solution", DbType="NVarChar(500)")]
		public string Solution
		{
			get
			{
				return this._Solution;
			}
			set
			{
				if ((this._Solution != value))
				{
					this.OnSolutionChanging(value);
					this.SendPropertyChanging();
					this._Solution = value;
					this.SendPropertyChanged("Solution");
					this.OnSolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsefullFileAdr", DbType="NVarChar(100)")]
		public string UsefullFileAdr
		{
			get
			{
				return this._UsefullFileAdr;
			}
			set
			{
				if ((this._UsefullFileAdr != value))
				{
					this.OnUsefullFileAdrChanging(value);
					this.SendPropertyChanging();
					this._UsefullFileAdr = value;
					this.SendPropertyChanged("UsefullFileAdr");
					this.OnUsefullFileAdrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsefullUrls", DbType="NVarChar(100)")]
		public string UsefullUrls
		{
			get
			{
				return this._UsefullUrls;
			}
			set
			{
				if ((this._UsefullUrls != value))
				{
					this.OnUsefullUrlsChanging(value);
					this.SendPropertyChanging();
					this._UsefullUrls = value;
					this.SendPropertyChanged("UsefullUrls");
					this.OnUsefullUrlsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MounthPeak", DbType="Int")]
		public System.Nullable<int> MounthPeak
		{
			get
			{
				return this._MounthPeak;
			}
			set
			{
				if ((this._MounthPeak != value))
				{
					this.OnMounthPeakChanging(value);
					this.SendPropertyChanging();
					this._MounthPeak = value;
					this.SendPropertyChanged("MounthPeak");
					this.OnMounthPeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Defecttbl_DeviceJoncDefecttbl", Storage="_DeviceJoncDefecttbls", ThisKey="DefectId", OtherKey="DefectId")]
		public EntitySet<DeviceJoncDefecttbl> DeviceJoncDefecttbls
		{
			get
			{
				return this._DeviceJoncDefecttbls;
			}
			set
			{
				this._DeviceJoncDefecttbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeviceJoncDefecttbls(DeviceJoncDefecttbl entity)
		{
			this.SendPropertyChanging();
			entity.Defecttbl = this;
		}
		
		private void detach_DeviceJoncDefecttbls(DeviceJoncDefecttbl entity)
		{
			this.SendPropertyChanging();
			entity.Defecttbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceJoncDefecttbl")]
	public partial class DeviceJoncDefecttbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DevJoncDefId;
		
		private System.Nullable<int> _DeviceId;
		
		private System.Nullable<int> _DefectId;
		
		private EntityRef<Defecttbl> _Defecttbl;
		
		private EntityRef<Devicetbl> _Devicetbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDevJoncDefIdChanging(int value);
    partial void OnDevJoncDefIdChanged();
    partial void OnDeviceIdChanging(System.Nullable<int> value);
    partial void OnDeviceIdChanged();
    partial void OnDefectIdChanging(System.Nullable<int> value);
    partial void OnDefectIdChanged();
    #endregion
		
		public DeviceJoncDefecttbl()
		{
			this._Defecttbl = default(EntityRef<Defecttbl>);
			this._Devicetbl = default(EntityRef<Devicetbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DevJoncDefId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DevJoncDefId
		{
			get
			{
				return this._DevJoncDefId;
			}
			set
			{
				if ((this._DevJoncDefId != value))
				{
					this.OnDevJoncDefIdChanging(value);
					this.SendPropertyChanging();
					this._DevJoncDefId = value;
					this.SendPropertyChanged("DevJoncDefId");
					this.OnDevJoncDefIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="Int")]
		public System.Nullable<int> DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					if (this._Devicetbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDeviceIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceId = value;
					this.SendPropertyChanged("DeviceId");
					this.OnDeviceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefectId", DbType="Int")]
		public System.Nullable<int> DefectId
		{
			get
			{
				return this._DefectId;
			}
			set
			{
				if ((this._DefectId != value))
				{
					if (this._Defecttbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDefectIdChanging(value);
					this.SendPropertyChanging();
					this._DefectId = value;
					this.SendPropertyChanged("DefectId");
					this.OnDefectIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Defecttbl_DeviceJoncDefecttbl", Storage="_Defecttbl", ThisKey="DefectId", OtherKey="DefectId", IsForeignKey=true)]
		public Defecttbl Defecttbl
		{
			get
			{
				return this._Defecttbl.Entity;
			}
			set
			{
				Defecttbl previousValue = this._Defecttbl.Entity;
				if (((previousValue != value) 
							|| (this._Defecttbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Defecttbl.Entity = null;
						previousValue.DeviceJoncDefecttbls.Remove(this);
					}
					this._Defecttbl.Entity = value;
					if ((value != null))
					{
						value.DeviceJoncDefecttbls.Add(this);
						this._DefectId = value.DefectId;
					}
					else
					{
						this._DefectId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Defecttbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Devicetbl_DeviceJoncDefecttbl", Storage="_Devicetbl", ThisKey="DeviceId", OtherKey="DeviceId", IsForeignKey=true)]
		public Devicetbl Devicetbl
		{
			get
			{
				return this._Devicetbl.Entity;
			}
			set
			{
				Devicetbl previousValue = this._Devicetbl.Entity;
				if (((previousValue != value) 
							|| (this._Devicetbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Devicetbl.Entity = null;
						previousValue.DeviceJoncDefecttbls.Remove(this);
					}
					this._Devicetbl.Entity = value;
					if ((value != null))
					{
						value.DeviceJoncDefecttbls.Add(this);
						this._DeviceId = value.DeviceId;
					}
					else
					{
						this._DeviceId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Devicetbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Devicetbl")]
	public partial class Devicetbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DeviceId;
		
		private string _DeviceManufacturer;
		
		private string _DeviceName;
		
		private System.Nullable<int> _MounthPeak;
		
		private EntitySet<DeviceJoncDefecttbl> _DeviceJoncDefecttbls;
		
		private EntitySet<ordertbl> _ordertbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeviceIdChanging(int value);
    partial void OnDeviceIdChanged();
    partial void OnDeviceManufacturerChanging(string value);
    partial void OnDeviceManufacturerChanged();
    partial void OnDeviceNameChanging(string value);
    partial void OnDeviceNameChanged();
    partial void OnMounthPeakChanging(System.Nullable<int> value);
    partial void OnMounthPeakChanged();
    #endregion
		
		public Devicetbl()
		{
			this._DeviceJoncDefecttbls = new EntitySet<DeviceJoncDefecttbl>(new Action<DeviceJoncDefecttbl>(this.attach_DeviceJoncDefecttbls), new Action<DeviceJoncDefecttbl>(this.detach_DeviceJoncDefecttbls));
			this._ordertbls = new EntitySet<ordertbl>(new Action<ordertbl>(this.attach_ordertbls), new Action<ordertbl>(this.detach_ordertbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this.OnDeviceIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceId = value;
					this.SendPropertyChanged("DeviceId");
					this.OnDeviceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceManufacturer", DbType="NVarChar(50)")]
		public string DeviceManufacturer
		{
			get
			{
				return this._DeviceManufacturer;
			}
			set
			{
				if ((this._DeviceManufacturer != value))
				{
					this.OnDeviceManufacturerChanging(value);
					this.SendPropertyChanging();
					this._DeviceManufacturer = value;
					this.SendPropertyChanged("DeviceManufacturer");
					this.OnDeviceManufacturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceName", DbType="NVarChar(50)")]
		public string DeviceName
		{
			get
			{
				return this._DeviceName;
			}
			set
			{
				if ((this._DeviceName != value))
				{
					this.OnDeviceNameChanging(value);
					this.SendPropertyChanging();
					this._DeviceName = value;
					this.SendPropertyChanged("DeviceName");
					this.OnDeviceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MounthPeak", DbType="Int")]
		public System.Nullable<int> MounthPeak
		{
			get
			{
				return this._MounthPeak;
			}
			set
			{
				if ((this._MounthPeak != value))
				{
					this.OnMounthPeakChanging(value);
					this.SendPropertyChanging();
					this._MounthPeak = value;
					this.SendPropertyChanged("MounthPeak");
					this.OnMounthPeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Devicetbl_DeviceJoncDefecttbl", Storage="_DeviceJoncDefecttbls", ThisKey="DeviceId", OtherKey="DeviceId")]
		public EntitySet<DeviceJoncDefecttbl> DeviceJoncDefecttbls
		{
			get
			{
				return this._DeviceJoncDefecttbls;
			}
			set
			{
				this._DeviceJoncDefecttbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Devicetbl_ordertbl", Storage="_ordertbls", ThisKey="DeviceId", OtherKey="DeviceId")]
		public EntitySet<ordertbl> ordertbls
		{
			get
			{
				return this._ordertbls;
			}
			set
			{
				this._ordertbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeviceJoncDefecttbls(DeviceJoncDefecttbl entity)
		{
			this.SendPropertyChanging();
			entity.Devicetbl = this;
		}
		
		private void detach_DeviceJoncDefecttbls(DeviceJoncDefecttbl entity)
		{
			this.SendPropertyChanging();
			entity.Devicetbl = null;
		}
		
		private void attach_ordertbls(ordertbl entity)
		{
			this.SendPropertyChanging();
			entity.Devicetbl = this;
		}
		
		private void detach_ordertbls(ordertbl entity)
		{
			this.SendPropertyChanging();
			entity.Devicetbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ordertbl")]
	public partial class ordertbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OrderId;
		
		private System.Nullable<int> _OwnerId;
		
		private System.Nullable<int> _DeviceId;
		
		private System.Nullable<int> _SrvId;
		
		private System.Nullable<bool> _RAM;
		
		private System.Nullable<bool> _Battery;
		
		private System.Nullable<bool> _charger;
		
		private string _TakeDate;
		
		private System.Nullable<bool> _CurrentStatus;
		
		private string _RepairedDate;
		
		private System.Nullable<int> _payment;
		
		private System.Nullable<int> _discount;
		
		private string _expretion;
		
		private EntitySet<Part> _Parts;
		
		private EntityRef<Devicetbl> _Devicetbl;
		
		private EntityRef<ownertbl> _ownertbl;
		
		private EntityRef<serviceman> _serviceman;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIdChanging(int value);
    partial void OnOrderIdChanged();
    partial void OnOwnerIdChanging(System.Nullable<int> value);
    partial void OnOwnerIdChanged();
    partial void OnDeviceIdChanging(System.Nullable<int> value);
    partial void OnDeviceIdChanged();
    partial void OnSrvIdChanging(System.Nullable<int> value);
    partial void OnSrvIdChanged();
    partial void OnRAMChanging(System.Nullable<bool> value);
    partial void OnRAMChanged();
    partial void OnBatteryChanging(System.Nullable<bool> value);
    partial void OnBatteryChanged();
    partial void OnchargerChanging(System.Nullable<bool> value);
    partial void OnchargerChanged();
    partial void OnTakeDateChanging(string value);
    partial void OnTakeDateChanged();
    partial void OnCurrentStatusChanging(System.Nullable<bool> value);
    partial void OnCurrentStatusChanged();
    partial void OnRepairedDateChanging(string value);
    partial void OnRepairedDateChanged();
    partial void OnpaymentChanging(System.Nullable<int> value);
    partial void OnpaymentChanged();
    partial void OndiscountChanging(System.Nullable<int> value);
    partial void OndiscountChanged();
    partial void OnexpretionChanging(string value);
    partial void OnexpretionChanged();
    #endregion
		
		public ordertbl()
		{
			this._Parts = new EntitySet<Part>(new Action<Part>(this.attach_Parts), new Action<Part>(this.detach_Parts));
			this._Devicetbl = default(EntityRef<Devicetbl>);
			this._ownertbl = default(EntityRef<ownertbl>);
			this._serviceman = default(EntityRef<serviceman>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerId", DbType="Int")]
		public System.Nullable<int> OwnerId
		{
			get
			{
				return this._OwnerId;
			}
			set
			{
				if ((this._OwnerId != value))
				{
					if (this._ownertbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOwnerIdChanging(value);
					this.SendPropertyChanging();
					this._OwnerId = value;
					this.SendPropertyChanged("OwnerId");
					this.OnOwnerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="Int")]
		public System.Nullable<int> DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					if (this._Devicetbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDeviceIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceId = value;
					this.SendPropertyChanged("DeviceId");
					this.OnDeviceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrvId", DbType="Int")]
		public System.Nullable<int> SrvId
		{
			get
			{
				return this._SrvId;
			}
			set
			{
				if ((this._SrvId != value))
				{
					if (this._serviceman.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSrvIdChanging(value);
					this.SendPropertyChanging();
					this._SrvId = value;
					this.SendPropertyChanged("SrvId");
					this.OnSrvIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM", DbType="Bit")]
		public System.Nullable<bool> RAM
		{
			get
			{
				return this._RAM;
			}
			set
			{
				if ((this._RAM != value))
				{
					this.OnRAMChanging(value);
					this.SendPropertyChanging();
					this._RAM = value;
					this.SendPropertyChanged("RAM");
					this.OnRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery", DbType="Bit")]
		public System.Nullable<bool> Battery
		{
			get
			{
				return this._Battery;
			}
			set
			{
				if ((this._Battery != value))
				{
					this.OnBatteryChanging(value);
					this.SendPropertyChanging();
					this._Battery = value;
					this.SendPropertyChanged("Battery");
					this.OnBatteryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_charger", DbType="Bit")]
		public System.Nullable<bool> charger
		{
			get
			{
				return this._charger;
			}
			set
			{
				if ((this._charger != value))
				{
					this.OnchargerChanging(value);
					this.SendPropertyChanging();
					this._charger = value;
					this.SendPropertyChanged("charger");
					this.OnchargerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakeDate", DbType="NVarChar(15)")]
		public string TakeDate
		{
			get
			{
				return this._TakeDate;
			}
			set
			{
				if ((this._TakeDate != value))
				{
					this.OnTakeDateChanging(value);
					this.SendPropertyChanging();
					this._TakeDate = value;
					this.SendPropertyChanged("TakeDate");
					this.OnTakeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatus", DbType="Bit")]
		public System.Nullable<bool> CurrentStatus
		{
			get
			{
				return this._CurrentStatus;
			}
			set
			{
				if ((this._CurrentStatus != value))
				{
					this.OnCurrentStatusChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatus = value;
					this.SendPropertyChanged("CurrentStatus");
					this.OnCurrentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepairedDate", DbType="NVarChar(15)")]
		public string RepairedDate
		{
			get
			{
				return this._RepairedDate;
			}
			set
			{
				if ((this._RepairedDate != value))
				{
					this.OnRepairedDateChanging(value);
					this.SendPropertyChanging();
					this._RepairedDate = value;
					this.SendPropertyChanged("RepairedDate");
					this.OnRepairedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment", DbType="Int")]
		public System.Nullable<int> payment
		{
			get
			{
				return this._payment;
			}
			set
			{
				if ((this._payment != value))
				{
					this.OnpaymentChanging(value);
					this.SendPropertyChanging();
					this._payment = value;
					this.SendPropertyChanged("payment");
					this.OnpaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Int")]
		public System.Nullable<int> discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				if ((this._discount != value))
				{
					this.OndiscountChanging(value);
					this.SendPropertyChanging();
					this._discount = value;
					this.SendPropertyChanged("discount");
					this.OndiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expretion", DbType="NVarChar(70)")]
		public string expretion
		{
			get
			{
				return this._expretion;
			}
			set
			{
				if ((this._expretion != value))
				{
					this.OnexpretionChanging(value);
					this.SendPropertyChanging();
					this._expretion = value;
					this.SendPropertyChanged("expretion");
					this.OnexpretionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ordertbl_Part", Storage="_Parts", ThisKey="OrderId", OtherKey="OrderId")]
		public EntitySet<Part> Parts
		{
			get
			{
				return this._Parts;
			}
			set
			{
				this._Parts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Devicetbl_ordertbl", Storage="_Devicetbl", ThisKey="DeviceId", OtherKey="DeviceId", IsForeignKey=true)]
		public Devicetbl Devicetbl
		{
			get
			{
				return this._Devicetbl.Entity;
			}
			set
			{
				Devicetbl previousValue = this._Devicetbl.Entity;
				if (((previousValue != value) 
							|| (this._Devicetbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Devicetbl.Entity = null;
						previousValue.ordertbls.Remove(this);
					}
					this._Devicetbl.Entity = value;
					if ((value != null))
					{
						value.ordertbls.Add(this);
						this._DeviceId = value.DeviceId;
					}
					else
					{
						this._DeviceId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Devicetbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ownertbl_ordertbl", Storage="_ownertbl", ThisKey="OwnerId", OtherKey="OwnerId", IsForeignKey=true)]
		public ownertbl ownertbl
		{
			get
			{
				return this._ownertbl.Entity;
			}
			set
			{
				ownertbl previousValue = this._ownertbl.Entity;
				if (((previousValue != value) 
							|| (this._ownertbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ownertbl.Entity = null;
						previousValue.ordertbls.Remove(this);
					}
					this._ownertbl.Entity = value;
					if ((value != null))
					{
						value.ordertbls.Add(this);
						this._OwnerId = value.OwnerId;
					}
					else
					{
						this._OwnerId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ownertbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="serviceman_ordertbl", Storage="_serviceman", ThisKey="SrvId", OtherKey="SrvId", IsForeignKey=true)]
		public serviceman serviceman
		{
			get
			{
				return this._serviceman.Entity;
			}
			set
			{
				serviceman previousValue = this._serviceman.Entity;
				if (((previousValue != value) 
							|| (this._serviceman.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._serviceman.Entity = null;
						previousValue.ordertbls.Remove(this);
					}
					this._serviceman.Entity = value;
					if ((value != null))
					{
						value.ordertbls.Add(this);
						this._SrvId = value.SrvId;
					}
					else
					{
						this._SrvId = default(Nullable<int>);
					}
					this.SendPropertyChanged("serviceman");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Parts(Part entity)
		{
			this.SendPropertyChanging();
			entity.ordertbl = this;
		}
		
		private void detach_Parts(Part entity)
		{
			this.SendPropertyChanging();
			entity.ordertbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ownertbl")]
	public partial class ownertbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OwnerId;
		
		private string _owner;
		
		private string _PhoneNumber;
		
		private EntitySet<ordertbl> _ordertbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOwnerIdChanging(int value);
    partial void OnOwnerIdChanged();
    partial void OnownerChanging(string value);
    partial void OnownerChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public ownertbl()
		{
			this._ordertbls = new EntitySet<ordertbl>(new Action<ordertbl>(this.attach_ordertbls), new Action<ordertbl>(this.detach_ordertbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OwnerId
		{
			get
			{
				return this._OwnerId;
			}
			set
			{
				if ((this._OwnerId != value))
				{
					this.OnOwnerIdChanging(value);
					this.SendPropertyChanging();
					this._OwnerId = value;
					this.SendPropertyChanged("OwnerId");
					this.OnOwnerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner", DbType="NVarChar(50)")]
		public string owner
		{
			get
			{
				return this._owner;
			}
			set
			{
				if ((this._owner != value))
				{
					this.OnownerChanging(value);
					this.SendPropertyChanging();
					this._owner = value;
					this.SendPropertyChanged("owner");
					this.OnownerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(40)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ownertbl_ordertbl", Storage="_ordertbls", ThisKey="OwnerId", OtherKey="OwnerId")]
		public EntitySet<ordertbl> ordertbls
		{
			get
			{
				return this._ordertbls;
			}
			set
			{
				this._ordertbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ordertbls(ordertbl entity)
		{
			this.SendPropertyChanging();
			entity.ownertbl = this;
		}
		
		private void detach_ordertbls(ordertbl entity)
		{
			this.SendPropertyChanging();
			entity.ownertbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parts")]
	public partial class Part : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PartId;
		
		private System.Nullable<int> _OrderId;
		
		private string _PartName;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<int> _alarm;
		
		private string _AssembleDate;
		
		private System.Nullable<int> _MounthPeak;
		
		private EntityRef<ordertbl> _ordertbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartIdChanging(int value);
    partial void OnPartIdChanged();
    partial void OnOrderIdChanging(System.Nullable<int> value);
    partial void OnOrderIdChanged();
    partial void OnPartNameChanging(string value);
    partial void OnPartNameChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnalarmChanging(System.Nullable<int> value);
    partial void OnalarmChanged();
    partial void OnAssembleDateChanging(string value);
    partial void OnAssembleDateChanged();
    partial void OnMounthPeakChanging(System.Nullable<int> value);
    partial void OnMounthPeakChanged();
    #endregion
		
		public Part()
		{
			this._ordertbl = default(EntityRef<ordertbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PartId
		{
			get
			{
				return this._PartId;
			}
			set
			{
				if ((this._PartId != value))
				{
					this.OnPartIdChanging(value);
					this.SendPropertyChanging();
					this._PartId = value;
					this.SendPropertyChanged("PartId");
					this.OnPartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int")]
		public System.Nullable<int> OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					if (this._ordertbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartName", DbType="NVarChar(30)")]
		public string PartName
		{
			get
			{
				return this._PartName;
			}
			set
			{
				if ((this._PartName != value))
				{
					this.OnPartNameChanging(value);
					this.SendPropertyChanging();
					this._PartName = value;
					this.SendPropertyChanged("PartName");
					this.OnPartNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alarm", DbType="Int")]
		public System.Nullable<int> alarm
		{
			get
			{
				return this._alarm;
			}
			set
			{
				if ((this._alarm != value))
				{
					this.OnalarmChanging(value);
					this.SendPropertyChanging();
					this._alarm = value;
					this.SendPropertyChanged("alarm");
					this.OnalarmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssembleDate", DbType="NVarChar(15)")]
		public string AssembleDate
		{
			get
			{
				return this._AssembleDate;
			}
			set
			{
				if ((this._AssembleDate != value))
				{
					this.OnAssembleDateChanging(value);
					this.SendPropertyChanging();
					this._AssembleDate = value;
					this.SendPropertyChanged("AssembleDate");
					this.OnAssembleDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MounthPeak", DbType="Int")]
		public System.Nullable<int> MounthPeak
		{
			get
			{
				return this._MounthPeak;
			}
			set
			{
				if ((this._MounthPeak != value))
				{
					this.OnMounthPeakChanging(value);
					this.SendPropertyChanging();
					this._MounthPeak = value;
					this.SendPropertyChanged("MounthPeak");
					this.OnMounthPeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ordertbl_Part", Storage="_ordertbl", ThisKey="OrderId", OtherKey="OrderId", IsForeignKey=true)]
		public ordertbl ordertbl
		{
			get
			{
				return this._ordertbl.Entity;
			}
			set
			{
				ordertbl previousValue = this._ordertbl.Entity;
				if (((previousValue != value) 
							|| (this._ordertbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ordertbl.Entity = null;
						previousValue.Parts.Remove(this);
					}
					this._ordertbl.Entity = value;
					if ((value != null))
					{
						value.Parts.Add(this);
						this._OrderId = value.OrderId;
					}
					else
					{
						this._OrderId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ordertbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.serviceman")]
	public partial class serviceman : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SrvId;
		
		private string _name;
		
		private string _LastName;
		
		private string _expert;
		
		private EntitySet<ordertbl> _ordertbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrvIdChanging(int value);
    partial void OnSrvIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnexpertChanging(string value);
    partial void OnexpertChanged();
    #endregion
		
		public serviceman()
		{
			this._ordertbls = new EntitySet<ordertbl>(new Action<ordertbl>(this.attach_ordertbls), new Action<ordertbl>(this.detach_ordertbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrvId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SrvId
		{
			get
			{
				return this._SrvId;
			}
			set
			{
				if ((this._SrvId != value))
				{
					this.OnSrvIdChanging(value);
					this.SendPropertyChanging();
					this._SrvId = value;
					this.SendPropertyChanged("SrvId");
					this.OnSrvIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(30)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expert", DbType="NVarChar(15)")]
		public string expert
		{
			get
			{
				return this._expert;
			}
			set
			{
				if ((this._expert != value))
				{
					this.OnexpertChanging(value);
					this.SendPropertyChanging();
					this._expert = value;
					this.SendPropertyChanged("expert");
					this.OnexpertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="serviceman_ordertbl", Storage="_ordertbls", ThisKey="SrvId", OtherKey="SrvId")]
		public EntitySet<ordertbl> ordertbls
		{
			get
			{
				return this._ordertbls;
			}
			set
			{
				this._ordertbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ordertbls(ordertbl entity)
		{
			this.SendPropertyChanging();
			entity.serviceman = this;
		}
		
		private void detach_ordertbls(ordertbl entity)
		{
			this.SendPropertyChanging();
			entity.serviceman = null;
		}
	}
	
	public partial class ChechOrderIdResult
	{
		
		private int _OrderId;
		
		public ChechOrderIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int NOT NULL")]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this._OrderId = value;
				}
			}
		}
	}
	
	public partial class ShearchPartResult
	{
		
		private int _شماره_قطعه;
		
		private string _نام_قطعه;
		
		private System.Nullable<int> _قیمت;
		
		private System.Nullable<int> _هشدار;
		
		private string _تاریخ_استفاده;
		
		public ShearchPartResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شماره قطعه]", Storage="_شماره_قطعه", DbType="Int NOT NULL")]
		public int شماره_قطعه
		{
			get
			{
				return this._شماره_قطعه;
			}
			set
			{
				if ((this._شماره_قطعه != value))
				{
					this._شماره_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_قیمت", DbType="Int")]
		public System.Nullable<int> قیمت
		{
			get
			{
				return this._قیمت;
			}
			set
			{
				if ((this._قیمت != value))
				{
					this._قیمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_هشدار", DbType="Int")]
		public System.Nullable<int> هشدار
		{
			get
			{
				return this._هشدار;
			}
			set
			{
				if ((this._هشدار != value))
				{
					this._هشدار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تاریخ استفاده]", Storage="_تاریخ_استفاده", DbType="NVarChar(15)")]
		public string تاریخ_استفاده
		{
			get
			{
				return this._تاریخ_استفاده;
			}
			set
			{
				if ((this._تاریخ_استفاده != value))
				{
					this._تاریخ_استفاده = value;
				}
			}
		}
	}
	
	public partial class ShowDefectSolutionResult
	{
		
		private string _Defect;
		
		private string _Solution;
		
		private string _UsefullFileAdr;
		
		private string _UsefullUrls;
		
		public ShowDefectSolutionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Defect", DbType="NVarChar(100)")]
		public string Defect
		{
			get
			{
				return this._Defect;
			}
			set
			{
				if ((this._Defect != value))
				{
					this._Defect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solution", DbType="NVarChar(500)")]
		public string Solution
		{
			get
			{
				return this._Solution;
			}
			set
			{
				if ((this._Solution != value))
				{
					this._Solution = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsefullFileAdr", DbType="NVarChar(100)")]
		public string UsefullFileAdr
		{
			get
			{
				return this._UsefullFileAdr;
			}
			set
			{
				if ((this._UsefullFileAdr != value))
				{
					this._UsefullFileAdr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsefullUrls", DbType="NVarChar(100)")]
		public string UsefullUrls
		{
			get
			{
				return this._UsefullUrls;
			}
			set
			{
				if ((this._UsefullUrls != value))
				{
					this._UsefullUrls = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceDefectResult
	{
		
		private string _ایراد;
		
		private string _راه_حل;
		
		private string _لینک_های_مفید;
		
		private string _فایل_های_مورد_نیاز;
		
		public ShowDeviceDefectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ایراد", DbType="NVarChar(100)")]
		public string ایراد
		{
			get
			{
				return this._ایراد;
			}
			set
			{
				if ((this._ایراد != value))
				{
					this._ایراد = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[راه حل]", Storage="_راه_حل", DbType="NVarChar(500)")]
		public string راه_حل
		{
			get
			{
				return this._راه_حل;
			}
			set
			{
				if ((this._راه_حل != value))
				{
					this._راه_حل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[لینک های مفید]", Storage="_لینک_های_مفید", DbType="NVarChar(100)")]
		public string لینک_های_مفید
		{
			get
			{
				return this._لینک_های_مفید;
			}
			set
			{
				if ((this._لینک_های_مفید != value))
				{
					this._لینک_های_مفید = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[فایل های مورد نیاز]", Storage="_فایل_های_مورد_نیاز", DbType="NVarChar(100)")]
		public string فایل_های_مورد_نیاز
		{
			get
			{
				return this._فایل_های_مورد_نیاز;
			}
			set
			{
				if ((this._فایل_های_مورد_نیاز != value))
				{
					this._فایل_های_مورد_نیاز = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceManufacturerResult
	{
		
		private string _DeviceManufacturer;
		
		public ShowDeviceManufacturerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceManufacturer", DbType="NVarChar(50)")]
		public string DeviceManufacturer
		{
			get
			{
				return this._DeviceManufacturer;
			}
			set
			{
				if ((this._DeviceManufacturer != value))
				{
					this._DeviceManufacturer = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceNamesResult
	{
		
		private string _DeviceName;
		
		public ShowDeviceNamesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceName", DbType="NVarChar(50)")]
		public string DeviceName
		{
			get
			{
				return this._DeviceName;
			}
			set
			{
				if ((this._DeviceName != value))
				{
					this._DeviceName = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceNamesbyCategorizingResult
	{
		
		private string _DeviceName;
		
		public ShowDeviceNamesbyCategorizingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceName", DbType="NVarChar(50)")]
		public string DeviceName
		{
			get
			{
				return this._DeviceName;
			}
			set
			{
				if ((this._DeviceName != value))
				{
					this._DeviceName = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceNSofSrvmanResult
	{
		
		private System.Nullable<int> _شماره_سفارش;
		
		private string _نام_گوشی;
		
		private string _نام_قطعه;
		
		private string _توضیحات;
		
		public ShowDeviceNSofSrvmanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شماره سفارش]", Storage="_شماره_سفارش", DbType="Int")]
		public System.Nullable<int> شماره_سفارش
		{
			get
			{
				return this._شماره_سفارش;
			}
			set
			{
				if ((this._شماره_سفارش != value))
				{
					this._شماره_سفارش = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام گوشی]", Storage="_نام_گوشی", DbType="NVarChar(50)")]
		public string نام_گوشی
		{
			get
			{
				return this._نام_گوشی;
			}
			set
			{
				if ((this._نام_گوشی != value))
				{
					this._نام_گوشی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(70)")]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceReapairingResult
	{
		
		private System.Nullable<int> _شماره_سفارش;
		
		private string _نام_گوشی;
		
		private string _نام_قطعه;
		
		private string _توضیحات;
		
		public ShowDeviceReapairingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شماره سفارش]", Storage="_شماره_سفارش", DbType="Int")]
		public System.Nullable<int> شماره_سفارش
		{
			get
			{
				return this._شماره_سفارش;
			}
			set
			{
				if ((this._شماره_سفارش != value))
				{
					this._شماره_سفارش = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام گوشی]", Storage="_نام_گوشی", DbType="NVarChar(50)")]
		public string نام_گوشی
		{
			get
			{
				return this._نام_گوشی;
			}
			set
			{
				if ((this._نام_گوشی != value))
				{
					this._نام_گوشی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(70)")]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceRepairedResult
	{
		
		private System.Nullable<int> _شماره_سفارش;
		
		private string _نام_گوشی;
		
		private string _نام_قطعه;
		
		private string _توضیحات;
		
		public ShowDeviceRepairedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شماره سفارش]", Storage="_شماره_سفارش", DbType="Int")]
		public System.Nullable<int> شماره_سفارش
		{
			get
			{
				return this._شماره_سفارش;
			}
			set
			{
				if ((this._شماره_سفارش != value))
				{
					this._شماره_سفارش = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام گوشی]", Storage="_نام_گوشی", DbType="NVarChar(50)")]
		public string نام_گوشی
		{
			get
			{
				return this._نام_گوشی;
			}
			set
			{
				if ((this._نام_گوشی != value))
				{
					this._نام_گوشی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(70)")]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
	}
	
	public partial class ShowDeviceSofSrvmanResult
	{
		
		private System.Nullable<int> _شماره_سفارش;
		
		private string _نام_گوشی;
		
		private string _نام_قطعه;
		
		private string _توضیحات;
		
		public ShowDeviceSofSrvmanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شماره سفارش]", Storage="_شماره_سفارش", DbType="Int")]
		public System.Nullable<int> شماره_سفارش
		{
			get
			{
				return this._شماره_سفارش;
			}
			set
			{
				if ((this._شماره_سفارش != value))
				{
					this._شماره_سفارش = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام گوشی]", Storage="_نام_گوشی", DbType="NVarChar(50)")]
		public string نام_گوشی
		{
			get
			{
				return this._نام_گوشی;
			}
			set
			{
				if ((this._نام_گوشی != value))
				{
					this._نام_گوشی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(70)")]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
	}
	
	public partial class ShowOrderMenuResult
	{
		
		private int _شماره_سفارش;
		
		private string _نام_گوشی;
		
		private string _نام_مشتری;
		
		private System.Nullable<bool> _رم;
		
		private System.Nullable<bool> _شارژر;
		
		private System.Nullable<bool> _باطری;
		
		private string _تاریخ_دریافت;
		
		private string _تاریخ_تعمیر;
		
		private System.Nullable<int> _پیش_پرداخت;
		
		private string _توضیحات;
		
		private string _نام_قطعه;
		
		private string _نام_تعمیرکار;
		
		private string _ن_خ_تعمیرکار;
		
		public ShowOrderMenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شماره سفارش]", Storage="_شماره_سفارش", DbType="Int NOT NULL")]
		public int شماره_سفارش
		{
			get
			{
				return this._شماره_سفارش;
			}
			set
			{
				if ((this._شماره_سفارش != value))
				{
					this._شماره_سفارش = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام گوشی]", Storage="_نام_گوشی", DbType="NVarChar(50)")]
		public string نام_گوشی
		{
			get
			{
				return this._نام_گوشی;
			}
			set
			{
				if ((this._نام_گوشی != value))
				{
					this._نام_گوشی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام مشتری]", Storage="_نام_مشتری", DbType="NVarChar(50)")]
		public string نام_مشتری
		{
			get
			{
				return this._نام_مشتری;
			}
			set
			{
				if ((this._نام_مشتری != value))
				{
					this._نام_مشتری = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_رم", DbType="Bit")]
		public System.Nullable<bool> رم
		{
			get
			{
				return this._رم;
			}
			set
			{
				if ((this._رم != value))
				{
					this._رم = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_شارژر", DbType="Bit")]
		public System.Nullable<bool> شارژر
		{
			get
			{
				return this._شارژر;
			}
			set
			{
				if ((this._شارژر != value))
				{
					this._شارژر = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_باطری", DbType="Bit")]
		public System.Nullable<bool> باطری
		{
			get
			{
				return this._باطری;
			}
			set
			{
				if ((this._باطری != value))
				{
					this._باطری = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تاریخ دریافت]", Storage="_تاریخ_دریافت", DbType="NVarChar(15)")]
		public string تاریخ_دریافت
		{
			get
			{
				return this._تاریخ_دریافت;
			}
			set
			{
				if ((this._تاریخ_دریافت != value))
				{
					this._تاریخ_دریافت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تاریخ تعمیر]", Storage="_تاریخ_تعمیر", DbType="NVarChar(15)")]
		public string تاریخ_تعمیر
		{
			get
			{
				return this._تاریخ_تعمیر;
			}
			set
			{
				if ((this._تاریخ_تعمیر != value))
				{
					this._تاریخ_تعمیر = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="پیش‎پرداخت", Storage="_پیش_پرداخت", DbType="Int")]
		public System.Nullable<int> پیش_پرداخت
		{
			get
			{
				return this._پیش_پرداخت;
			}
			set
			{
				if ((this._پیش_پرداخت != value))
				{
					this._پیش_پرداخت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(70)")]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام تعمیرکار]", Storage="_نام_تعمیرکار", DbType="NVarChar(20)")]
		public string نام_تعمیرکار
		{
			get
			{
				return this._نام_تعمیرکار;
			}
			set
			{
				if ((this._نام_تعمیرکار != value))
				{
					this._نام_تعمیرکار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ن خ تعمیرکار]", Storage="_ن_خ_تعمیرکار", DbType="NVarChar(30)")]
		public string ن_خ_تعمیرکار
		{
			get
			{
				return this._ن_خ_تعمیرکار;
			}
			set
			{
				if ((this._ن_خ_تعمیرکار != value))
				{
					this._ن_خ_تعمیرکار = value;
				}
			}
		}
	}
	
	public partial class ShowPartsResult
	{
		
		private int _شماره_قطعه;
		
		private string _نام_قطعه;
		
		private System.Nullable<int> _قیمت;
		
		private System.Nullable<int> _هشدار;
		
		private string _تاریخ_مصرف;
		
		public ShowPartsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شماره قطعه]", Storage="_شماره_قطعه", DbType="Int NOT NULL")]
		public int شماره_قطعه
		{
			get
			{
				return this._شماره_قطعه;
			}
			set
			{
				if ((this._شماره_قطعه != value))
				{
					this._شماره_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_قیمت", DbType="Int")]
		public System.Nullable<int> قیمت
		{
			get
			{
				return this._قیمت;
			}
			set
			{
				if ((this._قیمت != value))
				{
					this._قیمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_هشدار", DbType="Int")]
		public System.Nullable<int> هشدار
		{
			get
			{
				return this._هشدار;
			}
			set
			{
				if ((this._هشدار != value))
				{
					this._هشدار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تاریخ مصرف]", Storage="_تاریخ_مصرف", DbType="NVarChar(15)")]
		public string تاریخ_مصرف
		{
			get
			{
				return this._تاریخ_مصرف;
			}
			set
			{
				if ((this._تاریخ_مصرف != value))
				{
					this._تاریخ_مصرف = value;
				}
			}
		}
	}
	
	public partial class ShowPartsforDeviceResult
	{
		
		private string _نام_قطعه;
		
		public ShowPartsforDeviceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام قطعه]", Storage="_نام_قطعه", DbType="NVarChar(30)")]
		public string نام_قطعه
		{
			get
			{
				return this._نام_قطعه;
			}
			set
			{
				if ((this._نام_قطعه != value))
				{
					this._نام_قطعه = value;
				}
			}
		}
	}
	
	public partial class ShowSrvmanResult
	{
		
		private int _شماره;
		
		private string _نام;
		
		private string _نام_خانوادگی;
		
		public ShowSrvmanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_شماره", DbType="Int NOT NULL")]
		public int شماره
		{
			get
			{
				return this._شماره;
			}
			set
			{
				if ((this._شماره != value))
				{
					this._شماره = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_نام", DbType="NVarChar(20)")]
		public string نام
		{
			get
			{
				return this._نام;
			}
			set
			{
				if ((this._نام != value))
				{
					this._نام = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام خانوادگی]", Storage="_نام_خانوادگی", DbType="NVarChar(30)")]
		public string نام_خانوادگی
		{
			get
			{
				return this._نام_خانوادگی;
			}
			set
			{
				if ((this._نام_خانوادگی != value))
				{
					this._نام_خانوادگی = value;
				}
			}
		}
	}
	
	public partial class ShowSrvmanExpertResult
	{
		
		private string _expert;
		
		public ShowSrvmanExpertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expert", DbType="NVarChar(15)")]
		public string expert
		{
			get
			{
				return this._expert;
			}
			set
			{
				if ((this._expert != value))
				{
					this._expert = value;
				}
			}
		}
	}
	
	public partial class ShowDefectTypebyCategorizingResult
	{
		
		private string _DefectType;
		
		public ShowDefectTypebyCategorizingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefectType", DbType="NVarChar(50)")]
		public string DefectType
		{
			get
			{
				return this._DefectType;
			}
			set
			{
				if ((this._DefectType != value))
				{
					this._DefectType = value;
				}
			}
		}
	}
	
	public partial class ShowDefectTypeResult
	{
		
		private string _DefectType;
		
		public ShowDefectTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefectType", DbType="NVarChar(50)")]
		public string DefectType
		{
			get
			{
				return this._DefectType;
			}
			set
			{
				if ((this._DefectType != value))
				{
					this._DefectType = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
